{{- if and .Values.dex.enabled .Values.dex.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.dex.serviceAccount.automountServiceAccountToken }}
serviceaccounts.openshift.io/oauth-redirecturi.argocd: 'https://argocd.apps.oc46-devel.cloudlet-dev.com/api/dex/callback'
metadata:
  name: {{ template "argo-cd.dexServiceAccountName" . }}
{{- if .Values.dex.serviceAccount.annotations }}
  annotations:
  {{- range $key, $value := .Values.dex.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" .Values.dex.name "name" .Values.dex.name) | nindent 4 }}
{{- end }}
